spring.application.name=booklibrary

# HTML editierbar ohne Neustart Server
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/

#H2 Konsole
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.trace=false
spring.h2.console.settings.web-allow-others=false


#Datenbankkonfiguration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=e1-oSE5'Z}3>N07F-YzR
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# F?llt die Daten, nachdem das Schema von Hibernate generiert wurde
spring.jpa.defer-datasource-initialization=true

# F?hrt Datei im Klassenpfad aus und bef?llt Tabelle mit den Daten in der Datei
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=create

# Multipart-Einstellungen
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB










